spring:
  datasource:
    url: jdbc:postgresql://api.chosun.life:15432/devossian
    username: devossian
    password: cnl2020!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:


      host: api.chosun.life
      port: 16379
      password: cnl2020!
